### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by sr-tream** [igogo-x86/HexRaysPyTools#13]
![log](https://i.imgur.com/dPOSsvV.png)

**Comment by igogo-x86** [comment]
Hello! Do you use IDA with version less than 7.0? I've stopped supporting them. I hope to update README.md with descriptions of new features in near future and mention about required IDA Pro version.

**Comment by sr-tream** [comment]
Yeah, 6.8. Because it works a little faster. Thanks
