### ISSUE TITLE
Consider a git tag for compatibility

### ISSUE THREAD

**Issue by celophi** [igogo-x86/HexRaysPyTools#14]
I noticed in https://github.com/igogo-x86/HexRaysPyTools/issues/9 that at some point a fix was made for IDA 7.0 which seems to not be backwards compatible with earlier versions.

I was able to determine which commit has the breaking change, but this took some time. Would you consider tagging `1ed20b18e62cf2b4b746fd7778dd794` as the last commit to be compatible for IDA 6.x versions?

Alternatively, a release would also work.

**Comment by igogo-x86** [comment]
Are you sure everything works fine? First that I noticed when tried it myself was that all custom menus were disabled.

I have found a version where I didn't started a transfer yet and it's `a282006`

**Comment by celophi** [comment]
On a second check, you are right. Everything did not work fine. Thanks for finding a SHA that works :+1:

**Comment by igogo-x86** [comment]
Okay, than I've added `ida_6_8` tag
