### ISSUE TITLE
Helper AttributeError

### ISSUE THREAD

**Issue by ner0x652** [igogo-x86/HexRaysPyTools#2]
Hi,

I've encountered the issue shown in image when starting IDA 6.9.
What can be the problem?

Thank you!
![untitled](https://cloud.githubusercontent.com/assets/2598963/21924153/79517758-d980-11e6-97d9-c3e433446fb6.png)

**Comment by igogo-x86** [comment]
Hello! 
Did you get a message `"[ERROR] Failed to initialize Hex-Rays SDK"` in console? If so, there's something wrong with Hex-Rays decompiler

**Comment by ner0x652** [comment]
Yes, that message appears in the console.

**Comment by Komis7sarova** [comment]
Здравствуйте. Выходит такая ошибка, в начале дизассемблирования. В чем может быть проблема?
![default](https://user-images.githubusercontent.com/41300520/42769635-6fa8bd5e-892b-11e8-9d9f-cee8ef0821f3.jpg)
