### ISSUE TITLE
Creating structure members instead of vtables

### ISSUE THREAD

**Issue by leoetlino** [igogo-x86/HexRaysPyTools#21]
Is there a way to tell the structure builder what structure member should be created when it sees a given vtable?

The function I'm reversing is a constructor and is full of code like this:

```
  *(_QWORD *)(this + 0x118) = &`vtable for'agl::utl::Parameter<int>;
  agl::utl::ParameterBase::ParameterBase((agl::utl::ParameterBase *)(this + 0x138));
  *(_QWORD *)(this + 0x138) = &`vtable for'agl::utl::Parameter<float>;
  agl::utl::ParameterBase::ParameterBase((agl::utl::ParameterBase *)(this + 0x158));
  *(_QWORD *)(this + 0x158) = &`vtable for'agl::utl::Parameter<float>;
  agl::utl::ParameterBase::ParameterBase((agl::utl::ParameterBase *)(this + 0x178));
```

Right now, scanning `this` causes conflicting members:
* 0x118, the vtable pointer for the correct derived class (`agl::utl::Parameter<int>`)
* 0x118, the base class (`agl::utl::ParameterBase`)

Same for `agl::utl::Parameter<float>`, which cause two entries: one for the vtable pointer and another for the base class.

Is there a way to associate the vtable for `agl::utl::Parameter<int>` with `agl::utl::Parameter_int`, and the vtable for `agl::utl::Parameter<float>` with `agl::utl::Parameter<float>`, and so on? With small functions I can just disable the vtable members and fix the class types manually but this is infeasible for large classes which have hundreds of members.

I've noticed that the structure builder is sometimes able to guess the correct structure correctly, but not always.

**Comment by igogo-x86** [comment]
You mean to implement automatic decision about which virtual table to keep among several found?
Like for example in this situation:
![default](https://user-images.githubusercontent.com/22378463/45947842-67456680-bffe-11e8-8c8a-ab7b06c2be5d.png)
Where it's quite obvious that we should keep `EncryptorMessage`

**Comment by leoetlino** [comment]
Sorry, I wasn't clear enough. Let's consider an example:

```cpp
  agl::utl::ParameterBase::ParameterBase((agl::utl::ParameterBase *)(v1 + 0x158));
  *(_QWORD *)(v1 + 0x158) = &vtable for agl::utl::Parameter<bool>;

  agl::utl::ParameterBase::ParameterBase((agl::utl::ParameterBase *)(v1 + 0x178));
  *(_QWORD *)(v1 + 0x178) = &vtable for agl::utl::Parameter<int>;

  agl::utl::ParameterBase::ParameterBase((agl::utl::ParameterBase *)(v1 + 0x198));
  *(_QWORD *)(v1 + 0x198) = &vtable for agl::utl::Parameter<bool>;
```
(`agl::utl::ParameterBase` is the base class, and `agl::utl::Parameter<bool>` and `agl::utl::Parameter<int>` are derived classes)

![image](https://user-images.githubusercontent.com/4209061/45966219-c91bc580-c02a-11e8-8a6f-91a711d86431.png)
Currently the scanner is able to find the vtable for the derived class, and the base class. However, ideally it'd give something like this:
![image](https://user-images.githubusercontent.com/4209061/45966244-df298600-c02a-11e8-8525-12a9a3b1a200.png)

The weird thing is that this actually works in other cases, but not here. For example, if the scanner detects a vtable for `String`, it correctly suggests the member is a `String` and not just a String vtable pointer. For some reason this doesn't work with the Parameter classes, so I'm wondering if I'm doing something wrong.

**Comment by igogo-x86** [comment]
Try "Resolve" button. In the latest commit I tweaked it so as non-basic types would be more preferable than virtual tables and it should produce the effect you want.
Nice black theme by the way.

**Comment by leoetlino** [comment]
Oh, thank you very much! I'll close this issue since this solves the problem with large structures that have a lot of members. Thanks again!
