### ISSUE TITLE
Can we manually create vtables?

### ISSUE THREAD

**Issue by NyaMisty** [igogo-x86/HexRaysPyTools#23]
Often I come across class inlinely constructed on the stack.
![image](https://user-images.githubusercontent.com/5344431/50337541-6748fa00-054c-11e9-9529-7ee23c7e2740.png)
As variable like this does not has a pointer to class, the tool cannot perform a scan or deep scan.
I'm wondering if I can manually create a vtable or a class.

**Comment by NyaMisty** [comment]
Sorry for the late reply :( I forgot this issue at all.
And it works like a charm!
Thanks a lot for your work ;)

**Comment by unoexperto** [comment]
> I've committed a little update. So now it's possible to right click on address of possible vtable in IDA-View and select "Create Virtual Table" menu

@igogo-x86 Igor, I apologize for lame question but where do I find this menu ? I don't see it anywhere in version 7.2 :(
