### ISSUE TITLE
Structure builder shows `?` instead of type

### ISSUE THREAD

**Issue by vient** [igogo-x86/HexRaysPyTools#29]
Stack trace:
```
Traceback (most recent call last):
  File "C:/Program Files/IDA Pro 7.3/plugins\HexRaysPyTools\forms.py", line 94, in <lambda>
    btn_finalize.clicked.connect(lambda: self.structure_model.finalize())
  File "C:/Program Files/IDA Pro 7.3/plugins\HexRaysPyTools\core\temporary_structure.py", line 708, in finalize
    if self.pack():
  File "C:/Program Files/IDA Pro 7.3/plugins\HexRaysPyTools\core\temporary_structure.py", line 550, in pack
    cdecl = idaapi.asktext(0x10000, '#pragma pack(push, 1)\n' + cdecl, "The following new type will be created")
TypeError: cannot concatenate 'str' and 'NoneType' objects
```
Happened because type of one variable was set as `?`. After changing to `_QWORD` everything worked.

**Comment by igogo-x86** [comment]
Yeah, that's a bug. And what was the original variable type?

**Comment by vient** [comment]
It was automatically set to `?` so I needed to fix it. I guess it’s also a specific IDA 7.3 bug like my other issue #30. If your plugin has some kind of debug output, I can provide it (or may even try to fix myself).

**Comment by igogo-x86** [comment]
I mean you can try to find location where the information about this member was found (clicking on offset in structure reconstructor) and to see what type of variable (or other stuff) was there.

You can turn on debug messages at `IDADIR\cfg\HexRaysPyTools.cfg` by setting `debug_message_level` to 10

**Comment by igogo-x86** [comment]
More info about how to reproduce the issue?

**Comment by vient** [comment]
I wasn't able to reproduce it yet.

**Comment by vient** [comment]
I also want to clarify that I remember about this issue but I've used HexRaysPyTools extensively with IDA 7.3 since report and only saw this bug happened once.

I close the issue now and will reopen if I get better test case — i.e., any test case at all.
