### ISSUE TITLE
Classes window does not work in IDA 7.3

### ISSUE THREAD

**Issue by vient** [igogo-x86/HexRaysPyTools#30]
Opening "Classes" window after creating any class (with vtable) causes IDA 7.3 to crash with INTERR 918.

I'm trying to get some more info from Hex-Rays regarding this INTERR, currently they've said this INTERR means "a tinfo_t object was missing while it was expected to be present". I will update this issue if they will share more information.

**Comment by vient** [comment]
It works in IDA 7.2, so it seems only 7.3 is affected.

**Comment by igogo-x86** [comment]
Unfortunately I won't have an opportunity to reproduce it in the foreseeable future. I could try to play around with tiny example with simple inheritance if even it crashes at IDA 7.3

**Comment by vient** [comment]
I resolved this problem with Hex-Rays, they fixed it on the IDAPython side.
