### ISSUE TITLE
ImportError: DLL load failed while importing sip

### ISSUE THREAD

**Issue by Koluchy** [igogo-x86/HexRaysPyTools#48]
Hi!
In ida 7.4 after start i got next:
```
C:\Program Files\IDA Pro 7.4\plugins\HexRaysPyTools.py: DLL load failed while importing sip: Не найден указанный модуль.
Traceback (most recent call last):
  File "C:\Program Files\IDA Pro 7.4\python\3\ida_idaapi.py", line 593, in IDAPython_ExecScript
    exec(code, g)
  File "C:/Program Files/IDA Pro 7.4/plugins/HexRaysPyTools.py", line 8, in <module>
    from HexRaysPyTools.callbacks import hx_callback_manager, action_manager
  File "C:/Program Files/IDA Pro 7.4/plugins\HexRaysPyTools\callbacks\__init__.py", line 3, in <module>
    from . import form_requests
  File "C:/Program Files/IDA Pro 7.4/plugins\HexRaysPyTools\callbacks\form_requests.py", line 5, in <module>
    import HexRaysPyTools.core.classes as classes
  File "C:/Program Files/IDA Pro 7.4/plugins\HexRaysPyTools\core\classes.py", line 1, in <module>
    from PyQt5 import QtCore, QtGui
ImportError: DLL load failed while importing sip: Не найден указанный модуль.
```

At the same time:
In Windows cmd:
```
C:\python3>python
Python 3.8.1 (tags/v3.8.1:1b293b6, Dec 18 2019, 23:11:46) [MSC v.1916 64 bit (AM
D64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from PyQt5 import sip
>>>
```

And in Ida python cmd:
```
Python>from PyQt5 import sip
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: DLL load failed while importing sip: Не найден указанный модуль.
Python>import sys
Python>sys.version
'3.8.1 (tags/v3.8.1:1b293b6, Dec 18 2019, 23:11:46) [MSC v.1916 64 bit (AMD64)]'
```

Ida 7.4.191112 x64, Win7 x64.
Is this a bug or am I doing something wrong? 
Thanks.

**Comment by p-state** [comment]
I think something is wrong with your PyQt5 package. Try to reinstall Python. You can also try to install Python 3.7.x

**Comment by Koluchy** [comment]
Thanks. Installing Python version 3.7.6 helped.

**Comment by 0xTowel** [comment]
For others who may stumble across this issue:

You can still use 3.8, you just need to replace the bugged `sip.pyd` file with a patched one.

HexRays addressed this in a blog post:

> "When trying to use PyQt, IDA crashes. Unfortunately, in Python 3.8 the layout of some internal structures has changed and SIP (the API bindings library used by PyQt) tries to access wrong data. Notably, this issue also affects Linux and Mac versions of IDAPython. If you are affected by this, you can download an updated build of the sip module below."

https://www.hex-rays.com/blog/ida-7-4-and-python-3-8/

**Comment by TheEpicFace007** [comment]
Where do I find a a patched sip.pyd? @0xTowel

**Comment by 0xTowel** [comment]
> 
> 
> Where do I find a a patched sip.pyd? @0xTowel

The downloads for the different OSs are located at the URL I posted above

**Comment by shrddr** [comment]
in newer versions you don't need to download anything but run `idapyswitch.exe` and it will apply a correct version of `sip.pyd`
