### ISSUE TITLE
Failed to register "Edit/Open subviews/Classes"

### ISSUE THREAD

**Issue by HexRabbit** [igogo-x86/HexRaysPyTools#54]
The bug is caused by attaching the not-yet registered name to menu,
https://github.com/igogo-x86/HexRaysPyTools/blob/2826a7b0721d908f854296d5df1c1116cb8ef52c/HexRaysPyTools/callbacks/form_requests.py#L59-L60
since `ActionManager.register` doesn't register the action immediately but register it when `ActionManager.initialize` is called.
https://github.com/igogo-x86/HexRaysPyTools/blob/2826a7b0721d908f854296d5df1c1116cb8ef52c/HexRaysPyTools/callbacks/actions.py#L10-L20

Maybe I can move the registration part below to `ActionManager.register` and eliminate  `ActionManager.initialize` ? 
https://github.com/igogo-x86/HexRaysPyTools/blob/2826a7b0721d908f854296d5df1c1116cb8ef52c/HexRaysPyTools/callbacks/actions.py#L17-L19

**Comment by HexRabbit** [comment]
Found issue #30, since I'm using IDA 7.0, I don't know if there's any change on IDA 7.4,
but I can confirm that after the registration part fix it works on IDA 7.0

**Comment by igogo-x86** [comment]
Closed by #55
