### ISSUE TITLE
Identifying structure inline functions

### ISSUE THREAD

**Issue by MegaBor** [igogo-x86/HexRaysPyTools#57]
I saw this post over reverseengineering, wondering if it is possible to do that using HexRaysPyTools?
https://reverseengineering.stackexchange.com/questions/23125/ida-hex-rays-structure-inline-functions-recognition

**Comment by igogo-x86** [comment]
You may want to take a look at this plugin https://github.com/sibears/HRAST

It can be used to write some patterns and do some actions on the match.
