### ISSUE TITLE
Structure fields xrefs doesn't work from Structures Window

### ISSUE THREAD

**Issue by MegaBor** [igogo-x86/HexRaysPyTools#58]
When I do CTRL+X on a member variable in the Structures window of IDA in order to find xrefs, it says:
"There are no xrefs to Class.field_xx"
but from actual code it works smoothly.

**Comment by p-state** [comment]
This is actually IDA's feature, not this plugin. And it is intended to work with "IDA View".

**Comment by igogo-x86** [comment]
Yeah, that's because it is IDA's functionality and not plugin's. Plugin looks for structure cross-references using CTRL+X in decompiler view and since IDA 7.4 (7.3 ?) this feature became available without plugin (SHIFT+X)
