### ISSUE TITLE
Create Virtual Table error

### ISSUE THREAD

**Issue by TakahiroHaruyamaCb** [igogo-x86/HexRaysPyTools#59]
Hi,

I used HexRaysPyTools to create vftable structures by selecting the vftable then "Create Virtual Table" or making object structures on Structure Builder, but I got the following error.

Syntax error near: azure::storage::storage_exception
Syntax error near: }
[Error] Failed to create virtual table DebugPortServer_vtbl
****************************************************************************************************
struct DebugPortServer_vtbl
{
    azure::storage::storage_exception *(__fastcall __spoils<rcx,rdx,r8,r9,r10,r11,xmm0,xmm4,xmm5> *azure::storage::storage_exception::_scalar_deleting_destructor_uint)(azure::storage::storage_exception *this, char a2);
    char (__fastcall *fn_l_DebugPortServer_AuthenticateRequest)(__int64 a1, __int64 a2, DWORD a3, __int64 a4, _BYTE *a5);
    __int64 (__fastcall *fn_a_DebugPortServer_ProcessDebugRequest)(__int64 a1, __int64 a2, unsigned int a3, __int64 a4, unsigned int a5);
};

****************************************************************************************************

Any thought? Thanks.

**Comment by igogo-x86** [comment]
Seems like it can't understand this part `__spoils<rcx,rdx,r8,r9,r10,r11,xmm0,xmm4,xmm5>`. Just remove them from function type declaration

**Comment by TakahiroHaruyamaCb** [comment]
Thanks!
