### ISSUE TITLE
unknown op type

### ISSUE THREAD

**Issue by lab313ru** [igogo-x86/HexRaysPyTools#6]
http://wayback.archive.org/web/20131030004136/http://psxemulator.gazaxian.com/pSX_linux_1_13.tar.bz2

At this binary.

**Comment by igogo-x86** [comment]
And how to reproduce the error?

**Comment by lab313ru** [comment]
Plugin cannot be loaded into IDA, when opening this file.

**Comment by igogo-x86** [comment]
You can try latest version. Hope i didn't forget to check something this time
