### ISSUE TITLE
IDA Pro 7.2 Support ?

### ISSUE THREAD

**Issue by maskelihileci** [igogo-x86/HexRaysPyTools#60]
Hello, is there support I could not run in 7.2 version?

**Comment by igogo-x86** [comment]
What errors do you get? I don't have that IDA version and wanted to drop support however it was done in #43, I think.

Also in Releases you can find the last working with 7.2 version:
https://github.com/igogo-x86/HexRaysPyTools/releases

**Comment by sfinktah** [comment]
And now we get to IDA 7.5 support. :)   The errors (which I don't have at hand) were unsurprisingly related to the newer QT interface.  I would have a go at updating it myself, but I am still stuck working out how to get it to reload without restarting IDA.

**Comment by maskelihileci** [comment]
Sorry for my late reply.
The bulk of the problem stems from the python version.
IDA Pro 7.5 uses python 3.8
I tried to fix some of his errors manually but he said it was the missing module
No module named "common"
I guess it is possible to run it with minor adjustments

**Comment by sfinktah** [comment]
Works great with python 3.7 under ida pro 7.5, I've made a bunch of improvements so i'm familiar with how everything works, so I might be able to take a look on another machine running a later version of python.

**Comment by maskelihileci** [comment]
Thanks mate, we are waiting for the current version

**Comment by sfinktah** [comment]
I have it running now, how do I replicate the error?  I've tested all the things that I usually use HexRaysPyTools for, and nothing looks out of place.  You're welcome to try my branch at https://github.com/sfinktah/HexRaysPyTools

**Comment by maskelihileci** [comment]
It works fine now I didn't see any problems. 
Thank you for the update
