### ISSUE TITLE
Failed to create virtual table: _BOOL8 not recognised 

### ISSUE THREAD

**Issue by poul1x** [igogo-x86/HexRaysPyTools#71]
While doing deep scan I got `_BOOL8` return type in virtual function which failed structure builder.
I Fixed that with manual changing return type to `char`. 
Hope handling these situations will be done automatically.

```
Syntax error near: _BOOL8
Syntax error near: }
[Error] Failed to create virtual table CCreature_vtbl

struct CCreature_vtbl
{
    ...
    BOOL8 (__fastcall *sub_408FDC)(__int64 a1);
    ...
}
```

**Comment by arizvisa** [comment]
`_BOOL8` is kind of weird in that it's a type that IDA uses and renders, but isn't parseable by its regular parser. It needs to be explicitly created with `tinfo_t(0x28)`.
